### ISSUE TITLE
Running demo

### ISSUE THREAD

**Issue by mikeymckay** [gr2m/appcache-nanny#11]
I had to npm install hapi and moment to get it to run.

**Comment by gr2m** [comment]
Hmm, did you run `npm install`? Both hapi & moment are defined in the [package.json](https://github.com/gr2m/appcache-nanny/blob/master/package.json)

**Comment by mikeymckay** [comment]
Yeah... although I ended up having to install using sudo to make it work.
Perhaps my npm install s messed up.

**Comment by gr2m** [comment]
@mikeymckay yes, most likely. I'm quite sure you have to `chown` some directory to you current user, have seen that a lot  in the past.

But, just to be clear, is this still an issue? `I had to npm install hapi and moment to get it to run`

**Comment by mikeymckay** [comment]
Well, I got it working by doing sudo npm install ...

I also sent a pull request on a minor documentation issue but it failed in
Travis CI with a similar looking error, so it might be an actual issue.

**Comment by gr2m** [comment]
No Travis is unrelated, I'm looking into it right now, thanks!
