### ISSUE TITLE
Support Grunt-built apps… somehow

### ISSUE THREAD

**Issue by 47ronin** [gr2m/appcache-nanny#15]
Appcache-Nanny works like a charm on single-page apps that aren't processed through a task-runner. However, when using Grunt to compile everything into `dist/` then it doesn't work. I configured `Gruntfile.js` to port all the scripts, loader, and manifest into `dist/` but now the compiled app http requests always report back 200 instead of 304. For reference, I added Appcache-Nanny via Bower to a project created by Yeoman with the Angular generator.

**Comment by gr2m** [comment]
That shouldn’t be a problem, wether your server returns 200 or 304 has nothing to do with appcache-nanny, it’s a front-end library. When you use Grunt to build your assets into `dist/`, you need a custom task that generates the appcache manifest file for the `dist/` files
