### ISSUE TITLE
Breaks when build minified

### ISSUE THREAD

**Issue by GeorgeChackungal** [gr2m/appcache-nanny#29]
Hi,

My automated builds are failing because the ";" after use script is misplaced. Can you please fix it? Otherwise this is an awesome project!!!
![2016-09-15 23_02_52-appcache-nanny js](https://cloud.githubusercontent.com/assets/2109405/18560314/aa4a5848-7b98-11e6-9ef7-b1045c0bb6a1.png)

**Comment by gr2m** [comment]
can you send a pull request? As long as the standard linting passes, I’ll merge it in

**Comment by GeorgeChackungal** [comment]
Works fine now.
