### ISSUE TITLE
How to know if the caching is done for the first time?

### ISSUE THREAD

**Issue by GeorgeChackungal** [gr2m/appcache-nanny#34]
Hi,

I want to notify the user only if a new version is available. but not the first time it caches.

I tried the updateready event but it gets called even for the first time.

Any workaround?

**Comment by gr2m** [comment]
It’s been a while since I used this myself. But I’m very certain that there was a way. Can you check for the value of `.hasUpdate()`? It should be false on initial `updateready` event

**Comment by stereobooster** [comment]
`appCacheNanny.on('cached', () => {})` ?

**Comment by gr2m** [comment]
I think that was it, thanks @stereobooster
