### ISSUE TITLE
doubled applicationCache events (seen in latest Chrome stable)

### ISSUE THREAD

**Issue by gr2m** [gr2m/appcache-nanny#7]
to reproduce

1. start the demo server https://github.com/gr2m/appcache-nanny#demo
2. Open http://localhost:8888/
3. Click on `[Check for update]`
4. Reload page
5. Click on `[Check for update]`

You now see the `Application Cache Checking event` & `Application Cache NoUpdate event` twice.

I found out that `applicationCache.status` becomes `1` in the HTML file after step `4.`, although it lacks the `<html manifest="..">` attribute. This should not be possible, or it's another thing I've missed or they don't say in the appCache Handbook™. 

Anyway, the work around is pretty simple. When `applicationCache.status` is not `0` or `5`, don't load the iFrame, but use the `applicationCache` object of the host HTML file.

**Comment by mochtu** [comment]
I'm seeing the doubled messages too, the fix works for me. Are you gonna merge the fix into master?

**Comment by gr2m** [comment]
Yes, just setting up tests. I'm on it, give me a few more days

**Comment by gr2m** [comment]
I've released the `1.0.0` version, it's fixed in it.
